rabbitmq_logging:
  host: "localhost"
  port: "5672"
  username: guest
  password: guest #default credentials
  logging_level: INFO

db_config:
  user: "test_user"
  password: "Password1"
  host: "127.0.0.1"
  database: "archivation_system_db"

rabbitmq_connection:
  host: "localhost"
  virtual_host: "/"
  port: "5672"
  credentials:
    name: guest
    password: guest #default credentials
  enable_ssl:
    false
    #Server_name_id: str #optional
    #certificate_file: str-path
    #private_key_file: str-path
    #pk_password: str
    #CA_file: str-path
    #CA_path: str-path
    #CA_data: str-path

rabbitmq_info:
  consumer_ID: "Retimestamper"
  task_queue: "retimestamping"
  control_exchange: "control"

retimestamping_info:
  validity_length: 2
  TSA_info: #inforamtions about TSA ... in this case freetsa.org
    url: "https://freetsa.org/tsr"
    tsa_cert_path: "/home/server/Downloads/tsa.crt"
    tsa_crl_url: "https://www.freetsa.org/crl/root_ca.crl" #url to download crl for verification
    tsa_ca_pem: "/home/server/Downloads/cacert.pem"
