rabbitmq_connection:
  host: "localhost"
  virtual_host: "/"
  port: "5672"
  credentials:
    name: guest
    password: guest #default credentials
  enable_ssl:
    false
    #Server_name_id: str #optional
    #certificate_file: str-path
    #private_key_file: str-path
    #pk_password: str
    #CA_file: str-path
    #CA_path: str-path
    #CA_data: str-path
rabbitmq_logging:
  host: "localhost"
  port: "5672"
  username: guest
  password: guest #default credentials
  logging_level: INFO

rabbitmq_info:
  consumer_ID: "Archivator"
  task_queue: "archivation"
  control_exchange: "control"

db_config:
  user: "test_user"
  password: "Password1"
  host: "127.0.0.1"
  database: "archivation_system_db"

archivation_system_info:
  storage_dir_path: "/home/server/Desktop/" #path where archived files will be stored
  validity_length: 2
  signing_info:
    certificate_path: "/home/server/Desktop/cert.pem" #path to folder where certificate together with crl is stored
    private_key_path: "/home/server/Desktop/key.pem"
    pk_password: "Password1"
    crl_path: "" #not for now
  remote_access:
    False #information to be able to get files from remote nextcloud server or if you want to run this localy get false
    #host: '192.168.153.135'
    #port: 22
    #credentials:
    #  username: 'server'
    #  key_filepath: '' #path to authetication key for sftp
    #  password: '' #password to for authetication key file
  TSA_info: #inforamtions about TSA ... in this case freetsa.org
    url: "https://freetsa.org/tsr"
    tsa_cert_path: "/home/server/Downloads/tsa.crt"
    tsa_crl_url: "https://www.freetsa.org/crl/root_ca.crl" #url to download crl for verification
    tsa_ca_pem: "/home/server/Downloads/cacert.pem"
